Repository pedrozle/jotchua-bot, pull requests merged in 2023-09, with the labels that each got.

#6 update contributos
  docs/index.html
Labels: enhancement

#8 7 configurar discord py
  changelog.md
  main.py
  src/comandos/basic.py
  src/methods.py
Labels: good first issue

#21 18 quando faz o comando repita float frase dá erro e não responde
  main.py
  src/comandos/basic.py
Labels: bug

#23 22 adicionar comandos social
  main.py
  requirements.txt
  src/comandos/basic.py
  src/comandos/social.py
Labels: enhancement
